### ISSUE TITLE
Link CoC in top level nav

### ISSUE THREAD

**Issue by mjcollin** [UF-Carpentry/website#16]
CoC needs to be prominent and it was just updated.

https://carpentries.org/blog/2018/09/coc-revision-release/

https://carpentries.org/blog/2018/09/coc-revision-release/

**Comment by ha0ye** [comment]
Done, though it might be sensible to task some members of the board to copy over the Carpentries CoC, and think about what needs to be adjusted for our own purposes (e.g. reporting/handling of incidents).

**Comment by mjcollin** [comment]
Could we ask the Carpentries to act as our point of contact, even for not-quite-Carpentry events? Could this be one of their bullet point benefits of membership? I ask because handling issues is a skill that should have training and expertise to back it up.

**Comment by ha0ye** [comment]
I would guess that the reporting to Carpentries is mainly to deal with problematic instructors and attendees that shouldn't be allowed around future Carpentries events. I do think having a local response / reporting mechanism is important, even if that's just the board, and a possible escalation to UF.

**Comment by ha0ye** [comment]
Done in f576a24
