### ISSUE TITLE
Set up events calendar

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/website#2]
Might require some jekyll or JS magic, but establish an automatic calendar to keep track of the date and upcoming events.

**Comment by justinmillar** [comment]
Two potential options:

- Jekyll-based bootstrap calendar (e.g. https://github.com/NLKNguyen/jekyll-bootstrap-calendar)
- Google calender dropped in an iframe (I did something similar for http://www.r-gators.com/schedule/ ... although I never really updated it)

**Comment by ha0ye** [comment]
Another option is what I did here:
https://github.com/Open-Data-Science-at-SIO/Open-Data-Science-at-SIO.github.io/blob/master/events_list.html

It reads in the yaml front-matter for each "event" page, then generates a chronological list of future events. If we don't need an actual calendar display, but just icons for the workshops and meetings, this could work, too.

**Comment by justinmillar** [comment]
That is interesting, probably a good starting point for us. The bootstrap calendar uses a csv file to population the calendar, so if we decided we also want a calendar display we could write a script to collection of the front-matter information from the events md files into a csv.
