### ISSUE TITLE
Populate the website with basic content pages

### ISSUE THREAD

**Issue by ha0ye** [UF-Carpentry/website#3]
* About us / mission statement / code of conduct
* News / Blog
* Schedule of events
* Board, elections
* Meeting minutes
* Club charter / travel awards / other policies
* Contact info / links to other resources

**Comment by mjcollin** [comment]
Left to do:

- [ ] Backfill all prior workshops
- [ ] Code of conduct (not sure it was on original site)
- [ ] Workshop operations section
- [ ] News/posts setup

**Comment by ha0ye** [comment]
@mjcollin - I split out the Code of Conduct into its own section on the about page, and re-jiggered the news/posts setup.
