### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by elisemorrison** [UF-Carpentry/website#53]
Board meeting minutes after 7/28/2020 are not appearing on the website.

**Comment by ha0ye** [comment]
It’s rendering correctly at https://uf-carpentry.github.io/website/minutes/, so I suspect this is an issue on my netlify account that pushes to ufcarpentries.org

**Comment by ha0ye** [comment]
Now fixed?

**Comment by elisemorrison** [comment]
Yes - it looks good! Thanks so much Hao!
