### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by stuckyb** [UF-Carpentry/website#58]
I just heard from someone that the UF Carpentries website is down, and I confirmed on my machine.  I have not investigated in any detail, but from some quick preliminary checks, I wonder if there might be a DNS issue causing the problem.

**Comment by Cactusolo** [comment]
It works fine on my side (outside UF).

**Comment by stuckyb** [comment]
Oh, interesting.  Thanks for testing that, @Cactusolo!  That is curious, because I am currently at home and not on UF's network, but it still doesn't work for me.  It does look like something is wrong with name resolution (not everywhere, evidently).  http://www.uf-carpentries.org/ doesn't work, but the default pages site, https://uf-carpentry.github.io/website/events/, does.

**Comment by Cactusolo** [comment]
Not sure the reason. But I accessed via http://www.uf-carpentries.org/ <http://www.uf-carpentries.org/>



**********************************

Dr. Miao Sun

Email: cactusresponsible@gmail.com
Website: www.sunmiao.name
Twitter: @Miao_the_Sun

**Comment by gaurav** [comment]
I tried to run `dig  uf-carpentries.org` from here in North Carolina, and it seems to be jumping between correct resolution and a DNS SERVFAIL error. I think that means that one of the DNS servers hosting the domain is failing intermittently? Hopefully whoever's running it will figure it out soon.

**Comment by stuckyb** [comment]
That is similar to what I am seeing here, @gaurav, except that I only get lookup failures.  I'm afraid this one might be out of our hands until whomever is running the DNS servers gets it straightened out.  Thanks to both of you for helping test!

**Comment by stuckyb** [comment]
Looks like the website is back now.  I'll close the issue.
