### ISSUE TITLE
Fix mailing list e-mail address on website

### ISSUE THREAD

**Issue by gaurav** [UF-Carpentry/website#65]
On the website, links to the mailing list go to https://lists.ufl.edu/cgi-bin/wa?A0=INFORMATICS-TEACHING-L (e.g. at https://www.uf-carpentries.org/about/), but this link no longer works, and should be replaced with a working link.

**Comment by corybrunson** [comment]
@gaurav thanks for the tip. Though the link still works for me—from the button on the landing page and from the sidebar on the About page. (The link you posted also works for me.) Could this have to do with being logged in to a VPN or otherwise connected to UF? (I am on campus now.)

**Comment by corybrunson** [comment]
OK cool—i'm trying from a different location on campus and it still works. I'll try again when i get home to try to confirm your experience, and then i'll close the issue.

**Comment by corybrunson** [comment]
I get the same error when i try from home! That seems to resolve it. Thanks for checking. : )
